### PR TITLE
feat: add tests for Metadata serde and fix GetMetadata

### LINKED ISSUE #15: Add tests for metadata serde
Test that we serialize/deserialize correctly

### PR DESCRIPTION
**Pull request by verbotenj**
Closes #15

### CODE REVIEW

File: kupogo.go [hunk 1]
```diff
@@ -163,54 +163,67 @@ func (c *Client) GetMatches(pattern string) (*Matches, error) {
 	return matches, nil
 }
 
-func (c *Client) GetMetadata(slotNo int, txId string) (*Metadata, error) {
+func (c *Client) GetMetadata(slotNo int, txId string) ([]*Metadata, error) {
```
Comment (wolf31o2) [inline kupogo.go]: If the only use of Metadata returns a list, we should make Metadata a list.

```
type MetadataItem struct {
    Hash...
}

type Metadata []MetadataItem
```
Then, we just return *Metadata, error here

**Review by wolf31o2 — CHANGES_REQUESTED** [review]

File: kupogo.go [hunk 2]
```diff
@@ -165,52 +167,65 @@ func (c *Client) GetMatches(pattern string) (*Matches, error) {
...
-	if err != nil {
-		return nil, fmt.Errorf("failed to decode raw data: %s", err)
-	}
-	metadata := &Metadata{
-		Hash:   response.Hash,
-		Raw:    rawBytes,
-		Schema: response.Schema,
+
+	validate := validator.New()
+	var metadata Metadata
```
Comment (wolf31o2) [inline kupogo.go]: Use `metadata := &Metadata{}` and `return metadata, nil` at the end of the function

**Review by wolf31o2 — CHANGES_REQUESTED** [review]

**Review by wolf31o2 — APPROVED** [review]
